server:
  servlet:
    context-path: /

#Test
app:
  api:
    path:
      version:
        v1: "/api/v1"
      account:
        getAccount: "/account"
        createAccount: "account/sign-in"
      questionnaire:
        getQuestionnaireByDateRange: "/form/in-range"
        getQuestionnaireByDay: "/form/for-date"
        createQuestionnaire: "/form/create"
        updateQuestionnaire: "/form/update"
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm"